# Generated by Django 4.1.3 on 2023-02-17 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_remove_booking_last_name_booking_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='first_name',
            new_name='full_name',
        ),
    ]
